### ISSUE TITLE
Modulos do node

### ISSUE THREAD

**Issue by dicanoza** [wfuertes/surfschool#2]
Encontrei um problema para rodar o sever node, ele acusa a falta de um modulo o "eslint-config-airbnb-base"
se tentar instalar manualmente
npm install --save eslint-config-airbnb-base

Aparecem outros problemas:

/home/dicanoza/projects/surfschool/frontend/gulp/tasks/browserify.js
  39:9  error  Unary operator '--' used  no-plusplus

/home/dicanoza/projects/surfschool/frontend/src/containers/App.jsx
  22:15  error  Expected 'this' to be used by class method 'handleChange'  class-methods-use-this

/home/dicanoza/projects/surfschool/frontend/src/containers/RepoPage.jsx
  38:13  error  Expected 'this' to be used by class method 'renderUser'  class-methods-use-this

/home/dicanoza/projects/surfschool/frontend/src/containers/UserPage.jsx
  40:13  error  Expected 'this' to be used by class method 'renderRepo'  class-methods-use-this

/home/dicanoza/projects/surfschool/frontend/src/middleware/api.jsx
  73:33  error  Expected parentheses around arrow function argument having a body with curly braces  arrow-parens

✖ 5 problems (5 errors, 0 warnings)

**Comment by haisher** [comment]
O problema era uma configuração incorreta na lib do airbnb.
Foi resolvido e já pode ser retestado.

Antes:
`"extends": "airbnb-base",`

Depois:
`"extends": "airbnb",`

Tivemos que corrigir mais alguns warnings que o ESLINT jogou mas agora aparentemente está tudo ok.
